### PR TITLE
Yann/fix login system

### LINKED ISSUE #54: Insecure Login System
-  The login system currently lacks essential security features, making it accessible to anyone without restrictions.

- This poses a significant security risk as sensitive user information and access rights can be compromised.

- Implement secure authentication methods (e.g., encrypted connections, strong password policies, two-factor authentication) to safeguard the login process and protect user accounts.

### PR DESCRIPTION
**Pull request by Dharld**
## WHY
Closes #54 

## WHAT
Added a toast to avoid submitting a form with empty fields.

## TESTING
Screenshot_20250119_171837

### CODE REVIEW

File: src/components/LoginForm.jsx [hunk 1]
```diff
@@ -27,12 +27,20 @@ const LoginForm = () => {
 
   const showToast = useToast();
 
-  //
   // Function to handle the submission of the credentials
   const handleSubmit = (e) => {
     setIsLoading(true);
     e.preventDefault();
 
+    const { email, password } = credentials;
```
Comment (kouedelo) [inline src/components/LoginForm.jsx:35]: @Dharld , can you please checkout the following link to see how validation can be done using material UI forms? https://codesandbox.io/embed/cj8m3x?module=/SignInSide.tsx&fontsize=12

**Review by kouedelo — CHANGES_REQUESTED** [review]

**Review by kouedelo — APPROVED** [review]
